=== hifong/flying2/framework/WebRoot/WEB-INF/classes/xsd/application.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2012 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<!-- edited with XMLSpy v2011 (http://www.altova.com) by wanghaifeng (aspire) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="ST_locate">
		<xs:restriction base="xs:string">
			<xs:enumeration value="local"/>
			<xs:enumeration value="remote"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ST_config">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:element name="module">
		<xs:annotation>
			<xs:documentation>模块定义，id唯一</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_config">
					<xs:attribute name="id" type="xs:ID" use="required"/>
					<xs:attribute name="version" type="xs:string" use="required"/>
					<xs:attribute name="sort" type="xs:int" use="required"/>
					<xs:attribute name="locate" type="ST_locate" use="optional" default="local"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="config">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_config">
					<xs:attribute name="name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string"/>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="application">
		<xs:complexType>
			<xs:all>
				<xs:annotation>
					<xs:documentation>定义模块属性</xs:documentation>
				</xs:annotation>
				<xs:element name="id" type="xs:ID" />
				<xs:element name="event-producer" type="xs:string" />
				<xs:element name="product-mode" >
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="true"/>
							<xs:enumeration value="false"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="group-configs">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="configs" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="config" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="group" type="xs:string" use="optional"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="modules">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element ref="module"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hifong/flying2/framework/configs/application.xml
<?xml version="1.0" encoding="UTF-8"?>
<application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/application.xsd">
	<id>app001</id>
	<event-producer>0</event-producer>
	<product-mode>false</product-mode>
	<group-configs>
		<configs group="remoting">
			<config name="invoker">hessian</config>
			<config name="hessian">com.flying.common.remote.hessian.HessianRemoteServiceInvoker</config>
			<config name="thrift">com.flying.common.remote.thrift.ThriftRemoteServiceInvoker</config>
		</configs>
		<configs group="hessian">
			<config name="connectTimeout">10000</config>
			<config name="readTimeout">10000</config>
			<config name="debug">false</config>
			<config name="url">http://localhost:8080/remoting</config>
			<config name="hessian2Reply">true</config>
			<config name="hessian2Request">false</config>
			<config name="chunkedPost">true</config>
			<config name="maxConnection">2000</config>
			<config name="maxPerHostConnection">2000</config>
		</configs>
		<configs group="thrift1">
			<config name="port">10000</config>
		</configs>
		<configs group="http">
			<config name="requestTimeout">10000</config>
			<config name="soTimeout">10000</config>
			<config name="timeout">10000</config>
		</configs>
		<configs group="mongodb">
			<config name="db.default">project</config>
			<config name="db.names">project</config>
			<config name="db.maxSize">600</config>
			<config name="db.waitTimeout">127.0.0.1</config>
			<config name="project.port">20000</config>
			<config name="project.db">project</config>
		</configs>
		<configs group="work">
			<config name="temp">/temp</config>
			<config name="modules">/modules</config>
		</configs>
	</group-configs>
	<modules>
	<!-- 
		<module id="admin" version="1" locate="local" sort="1">
			C:\flying\admin\WebRoot
		</module> -->
		<module id="cms" version="1" locate="local" sort="2"><!-- $webHome\WEB-INF\modules\admin -->
			C:\flying\cms\WebRoot
		</module>
		<module id="pas" version="1" locate="local" sort="3">
			C:\flying\pas\WebRoot
		</module>
		<module id="assets" version="1" locate="local" sort="5">
			C:\flying\assets\WebRoot
		</module>
		<module id="gallery" version="1" locate="local" sort="6">
			C:\flying\gallery\WebRoot
		</module>
		<module id="project" version="1" locate="local" sort="7">
			C:\flying\project\WebRoot
		</module>
	</modules>
</application>
